# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Jul  1 16:15:39 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class CRUDToolBar(wx.ToolBar):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CRUDToolBar.__init__
        kwds["style"] = wx.TB_NOICONS|wx.TB_NODIVIDER
        wx.ToolBar.__init__(self, *args, **kwds)
        self.AddLabelTool(wx.NewId(), "New", wx.Bitmap("/home/tin/facu/pi/src/images/document-new.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Create a new compound", "")
        self.AddLabelTool(wx.NewId(), "", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.AddLabelTool(wx.NewId(), "item", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CRUDToolBar.__set_properties
        self.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CRUDToolBar.__do_layout
        pass
        # end wxGlade

# end of class CRUDToolBar


