# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Jul  1 16:15:39 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class SystemFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SystemFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.list_ctrl_3 = wx.ListCtrl(self.notebook_1_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.toolbar = wx.Panel(self, -1)
        self.bitmap_button_1 = wx.BitmapButton(self, -1, wx.Bitmap("/home/tin/facu/pi/src/images/go-next.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_2 = wx.BitmapButton(self, -1, wx.Bitmap("/home/tin/facu/pi/src/images/go-previous.png", wx.BITMAP_TYPE_ANY))
        self.list_ctrl_2 = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.button_1 = wx.Button(self, -1, "Cancel")
        self.button_2 = wx.Button(self, -1, "Accept")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SystemFrame.__set_properties
        self.SetTitle("frame_1")
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        self.bitmap_button_2.SetSize(self.bitmap_button_2.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SystemFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_20 = wx.BoxSizer(wx.VERTICAL)
        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15.Add(self.text_ctrl_1, 0, wx.ALL, 3)
        sizer_9.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_14.Add(self.list_ctrl_3, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_14)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "tab1")
        sizer_7.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_7, 7, wx.EXPAND, 0)
        sizer_16.Add(self.toolbar, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_9, 4, wx.EXPAND, 0)
        sizer_10.Add(sizer_11, 2, wx.EXPAND, 0)
        sizer_17.Add(self.bitmap_button_1, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        sizer_17.Add(self.bitmap_button_2, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        sizer_10.Add(sizer_17, 1, wx.EXPAND, 0)
        sizer_10.Add(sizer_12, 2, wx.EXPAND, 0)
        sizer_8.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_2.Add(self.list_ctrl_2, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_18, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_1, 0, wx.ALL|wx.ALIGN_BOTTOM, 3)
        sizer_4.Add(self.button_2, 0, wx.ALL|wx.ALIGN_BOTTOM, 3)
        sizer_3.Add(sizer_4, 0, wx.EXPAND|wx.ALIGN_BOTTOM, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_19.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_19, 4, wx.EXPAND, 0)
        sizer_8.Add(sizer_20, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class SystemFrame


